DROP DATABASE IF EXISTS CIS571_P1;
CREATE DATABASE IF NOT EXISTS CIS571_P1;
USE CIS571_P1;

CREATE TABLE IF NOT EXISTS Users(
	username VARCHAR(20) NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,

	PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS Trails(
	trail VARCHAR(255) NOT NULL,
	username VARCHAR(20) NOT NULL,

	PRIMARY KEY (trail, username),
	FOREIGN KEY(username) REFERENCES Users(username)
		ON DELETE CASCADE
);
